name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: "latest"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
